"""Derived resources, built from TRAIN ONLY to avoid leakage (Protocol Part B).

B1  q_j : empirical emotion distribution of each marker (Laplace smoothing,
          global back-off for low-frequency markers).
B2  weak regime labels (redundancy / complementarity / conflict) per marker,
          derived from out-of-fold p_text (produced by the text-only baseline,
          Part B2 / E) and q_j via Jensen-Shannon divergence.
B3  PPMI graph over {markers} u {emotion groups} from train co-occurrence.

q_j and the PMI graph need no torch and run immediately. Weak labels require a
`p_text` file (sample_id -> 6-dim softmax) generated by the OOF baseline; the
labeling math lives here so Phase 2 only has to feed it predictions.

Usage:
    python -m care_fusion.resources --config configs/default.yaml --steps q,pmi
    python -m care_fusion.resources --config configs/default.yaml --steps weak \
        --ptext artifacts/p_text_oof.json
"""
from __future__ import annotations

import argparse
import json
import math
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import yaml

# Polarity grouping used by the weak-label rules (B2).
POS = {"positive", "interest"}
NEG = {"sadness", "anger", "fear"}
NEU = {"neutral"}


# --------------------------------------------------------------------------- #
# IO helpers                                                                   #
# --------------------------------------------------------------------------- #
def load_split(processed_dir: str, split: str) -> List[dict]:
    path = Path(processed_dir) / f"{split}.jsonl"
    with path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f]


def _markers_in_sample(rec: dict) -> List[str]:
    """Unique markers present in a sample (set semantics for co-occurrence)."""
    return list(dict.fromkeys(rec["marker_seq"]))


# --------------------------------------------------------------------------- #
# B1 — empirical marker->emotion distribution q_j                              #
# --------------------------------------------------------------------------- #
def build_q_table(train: List[dict], labels: List[str], alpha: float, tau: int) -> dict:
    C = len(labels)
    lab2id = {l: i for i, l in enumerate(labels)}

    # count(m, e) = # train samples containing m with label e
    counts: Dict[str, np.ndarray] = defaultdict(lambda: np.zeros(C))
    global_counts = np.zeros(C)
    for rec in train:
        e = lab2id[rec["label"]]
        global_counts[e] += 1
        for m in _markers_in_sample(rec):
            counts[m][e] += 1

    global_dist = (global_counts + alpha) / (global_counts.sum() + alpha * C)

    q_table, low_freq, freq = {}, {}, {}
    for m, c in counts.items():
        total = int(c.sum())
        freq[m] = total
        if total < tau:
            q_table[m] = global_dist.tolist()      # back-off
            low_freq[m] = True
        else:
            q_table[m] = ((c + alpha) / (c.sum() + alpha * C)).tolist()
            low_freq[m] = False

    return {
        "labels": labels,
        "alpha": alpha,
        "tau": tau,
        "global_dist": global_dist.tolist(),
        "q": q_table,           # marker -> [p0..p5]
        "freq": freq,           # marker -> train frequency
        "low_freq": low_freq,   # marker -> bool (use learned embedding branch)
    }


# --------------------------------------------------------------------------- #
# B3 — PPMI graph over markers u emotion groups                                #
# --------------------------------------------------------------------------- #
def build_pmi_graph(train: List[dict], labels: List[str], min_cooccur: int) -> dict:
    n = len(train)
    # "events" per sample = its unique markers + its emotion-group node
    node_count: Counter = Counter()
    pair_count: Counter = Counter()
    for rec in train:
        nodes = _markers_in_sample(rec) + [f"__EMO__{rec['label']}"]
        nodes = list(dict.fromkeys(nodes))
        for a in nodes:
            node_count[a] += 1
        for i in range(len(nodes)):
            for j in range(i + 1, len(nodes)):
                a, b = sorted((nodes[i], nodes[j]))
                pair_count[(a, b)] += 1

    nodes = sorted(node_count)
    node_idx = {nd: i for i, nd in enumerate(nodes)}
    edges = []
    for (a, b), c in pair_count.items():
        if c < min_cooccur:
            continue
        p_ab = c / n
        p_a = node_count[a] / n
        p_b = node_count[b] / n
        ppmi = max(0.0, math.log(p_ab / (p_a * p_b)))
        if ppmi > 0:
            edges.append([node_idx[a], node_idx[b], round(ppmi, 6)])

    node_types = ["emotion" if nd.startswith("__EMO__") else "marker" for nd in nodes]
    return {
        "labels": labels,
        "nodes": nodes,
        "node_types": node_types,
        "edges": edges,                # [i, j, ppmi] undirected
        "n_train": n,
    }


# --------------------------------------------------------------------------- #
# B2 — weak regime labels from out-of-fold p_text + q_j                        #
# --------------------------------------------------------------------------- #
def jsd(p: np.ndarray, q: np.ndarray) -> float:
    """Jensen-Shannon divergence (base 2), in [0, 1]."""
    p = np.asarray(p, float) + 1e-12
    q = np.asarray(q, float) + 1e-12
    p /= p.sum()
    q /= q.sum()
    m = 0.5 * (p + q)
    kl = lambda a, b: float(np.sum(a * (np.log2(a) - np.log2(b))))
    return 0.5 * kl(p, m) + 0.5 * kl(q, m)


def _polarity(dist: np.ndarray, labels: List[str], neu_margin: float = 0.10) -> str:
    """Argmax-polarity of a distribution; returns 'POS'/'NEG'/'NEU'."""
    mass = {"POS": 0.0, "NEG": 0.0, "NEU": 0.0}
    for p, lab in zip(dist, labels):
        if lab in POS:
            mass["POS"] += p
        elif lab in NEG:
            mass["NEG"] += p
        else:
            mass["NEU"] += p
    top = max(mass, key=mass.get)
    others = sorted(mass.values())[-2]
    # weak/ambiguous -> treat as NEU (per B2: "pol(p_text)=NEU/yếu")
    if mass[top] - others < neu_margin:
        return "NEU"
    return top


def build_weak_labels(
    train: List[dict],
    q_table: dict,
    p_text: Dict[str, List[float]],
    labels: List[str],
    delta_low_pct: float,
    delta_high_pct: float,
) -> dict:
    """Assign a weak regime label to each (sample, marker). Needs OOF p_text."""
    q = q_table["q"]
    global_dist = np.array(q_table["global_dist"])

    # First pass: collect all deltas to set percentile thresholds on train.
    per_marker = []  # (sample_id, marker, delta, pol_text, pol_q)
    for rec in train:
        sid = str(rec["id"])
        if sid not in p_text:
            continue
        pt = np.array(p_text[sid])
        pol_t = _polarity(pt, labels)
        for m in _markers_in_sample(rec):
            qm = np.array(q.get(m, global_dist))
            d = jsd(pt, qm)
            per_marker.append((sid, m, d, pol_t, _polarity(qm, labels)))

    deltas = np.array([x[2] for x in per_marker]) if per_marker else np.array([0.0])
    d_low = float(np.percentile(deltas, delta_low_pct))
    d_high = float(np.percentile(deltas, delta_high_pct))

    def regime(d, pol_t, pol_q):
        if d < d_low:
            return "redundancy"
        if d >= d_high and pol_t == "NEU":
            return "complementarity"
        if d >= d_high and pol_t != pol_q:
            return "conflict"
        return "complementarity"  # default

    labels_out = defaultdict(list)
    dist = Counter()
    for sid, m, d, pol_t, pol_q in per_marker:
        r = regime(d, pol_t, pol_q)
        dist[r] += 1
        labels_out[sid].append({"marker": m, "delta": round(d, 6), "regime": r})

    return {
        "delta_low": d_low,
        "delta_high": d_high,
        "regime_dist": dict(dist),
        "weak_labels": dict(labels_out),   # sample_id -> [{marker, delta, regime}]
    }


# --------------------------------------------------------------------------- #
# CLI                                                                          #
# --------------------------------------------------------------------------- #
def main(argv: Optional[List[str]] = None) -> None:
    ap = argparse.ArgumentParser(description="Build train-only resources (Part B)")
    ap.add_argument("--config", default="configs/default.yaml")
    ap.add_argument("--steps", default="q,pmi",
                    help="comma list of: q, pmi, weak")
    ap.add_argument("--ptext", default=None,
                    help="path to OOF p_text JSON (sample_id -> 6 probs); needed for 'weak'")
    args = ap.parse_args(argv)

    cfg = yaml.safe_load(Path(args.config).read_text(encoding="utf-8"))
    labels = cfg["labels"]
    rcfg = cfg["resources"]
    art = Path(cfg["paths"]["artifacts_dir"]).resolve()
    art.mkdir(parents=True, exist_ok=True)
    train = load_split(cfg["paths"]["processed_dir"], "train")
    steps = {s.strip() for s in args.steps.split(",")}

    if "q" in steps:
        q_table = build_q_table(train, labels, rcfg["laplace_alpha"], rcfg["low_freq_tau"])
        (art / "q_table.json").write_text(
            json.dumps(q_table, ensure_ascii=False, indent=2), encoding="utf-8")
        n_low = sum(q_table["low_freq"].values())
        print(f"[B1] q_table: {len(q_table['q'])} markers "
              f"({n_low} low_freq back-off) -> {art}/q_table.json")

    if "pmi" in steps:
        graph = build_pmi_graph(train, labels, rcfg["ppmi_min_cooccur"])
        (art / "pmi_graph.json").write_text(
            json.dumps(graph, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"[B3] pmi_graph: {len(graph['nodes'])} nodes, "
              f"{len(graph['edges'])} edges -> {art}/pmi_graph.json")

    if "weak" in steps:
        if not args.ptext:
            raise SystemExit("[B2] --ptext required (run the OOF text-only baseline first).")
        q_table = json.loads((art / "q_table.json").read_text(encoding="utf-8"))
        p_text = json.loads(Path(args.ptext).read_text(encoding="utf-8"))
        weak = build_weak_labels(train, q_table, p_text, labels,
                                 rcfg["delta_low_pct"], rcfg["delta_high_pct"])
        (art / "weak_labels.json").write_text(
            json.dumps(weak, ensure_ascii=False), encoding="utf-8")
        print(f"[B2] weak labels: thresholds δ_low={weak['delta_low']:.4f} "
              f"δ_high={weak['delta_high']:.4f}; dist={weak['regime_dist']}")


if __name__ == "__main__":
    main()
